CREATE TABLE orders (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    cost MONEY NOT NULL,
    dishes_id BIGSERIAL NOT NULL,
    user_id BIGSERIAL NOT NULL,
    datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (dishes_id) REFERENCES dishes (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);